/**
 * Render a parsed session as a Markdown document.
 *
 * For Copilot sessions this is a 1:1 replica of the Copilot CLI bundle's
 * `/share file` output — same headings, emoji, fenced-code rules, tool-arg
 * summaries, diff detection, and `<details>` collapsing. Other agents fall
 * back to the same skeleton; their entries reuse the role/kind mapping that
 * `parseSession` already normalised.
 *
 * The data layer is the shared `ParsedSession` from `@agent-session-exporter/core`,
 * so this renderer doesn't know which agent the session came from beyond
 * picking a header title.
 */
import type { ParsedSession, TimelineEntry, ToolDetail, ToolResultKind } from "@agent-session-exporter/core";

export interface RenderMarkdownOptions {
  /** Include reasoning entries (default true, mirroring `/share file`). */
  includeReasoning?: boolean;
  /** Additional Markdown injected after the header `[!NOTE]` block. */
  summary?: string;
  /** Footer line; `""` disables it. Default: agent-session-exporter credit. */
  footer?: string;
  /** Timestamp written into the "Exported" header field (default: now). */
  exportedAt?: Date;
  /** Data-source label; when set and not "events.jsonl", a fallback note is shown. */
  sourceLabel?: string;
}

export function renderSessionMarkdown(session: ParsedSession, opts: RenderMarkdownOptions = {}): string {
  const includeReasoning = opts.includeReasoning ?? true;
  const exportedAt = opts.exportedAt ?? new Date();
  const start = session.startedAt ? new Date(session.startedAt) : exportedAt;
  const duration = formatDuration(Math.max(0, Math.floor((exportedAt.getTime() - start.getTime()) / 1000)));
  const agentTitle = agentDisplay(session.agent);

  const visible = session.entries.filter((entry) => includeReasoning || entry.role !== "reasoning");

  const header =
    `# ${agentTitle}\n\n` +
    `> [!NOTE]\n` +
    `> - **Session ID:** \`${session.id}\`  \n` +
    `> - **Agent:** ${session.agent}  \n` +
    `> - **Started:** ${start.toLocaleString()}  \n` +
    `> - **Duration:** ${duration}  \n` +
    `> - **Exported:** ${exportedAt.toLocaleString()}  \n` +
    (session.cwd ? `> - **Cwd:** \`${session.cwd}\`  \n` : "") +
    `\n---\n\n`;

  const summaryBlock = opts.summary && opts.summary.trim()
    ? `${opts.summary.trim()}\n\n---\n\n`
    : "";

  const body = visible.map((entry) => {
    const elapsed = entry.timestamp
      ? formatDuration(Math.max(0, Math.floor((new Date(entry.timestamp).getTime() - start.getTime()) / 1000)))
      : "";
    const prefix = elapsed ? `<sub>⏱️ ${elapsed}</sub>\n\n` : "";
    return prefix + renderEntry(entry);
  }).join("\n---\n\n");

  const footer = opts.footer === ""
    ? ""
    : `\n---\n\n<sub>${opts.footer ?? "Generated by [agent-session-exporter](https://github.com/TMYTiMidlY/agent-session-exporter)"}</sub>\n`;

  return header + summaryBlock + body + footer;
}

function agentDisplay(agent: string): string {
  if (agent === "copilot") return "🤖 Copilot CLI Session";
  if (agent === "claude") return "🌀 Claude Code Session";
  if (agent === "codex") return "🌀 Codex CLI Session";
  return `🌀 ${agent} Session`;
}

function renderEntry(entry: TimelineEntry): string {
  if (entry.role === "tool" && entry.tool) return renderTool(entry.tool);
  if (entry.role === "user") return heading("👤 User", entry.text);
  if (entry.role === "assistant") return heading("💬 Copilot", entry.text);
  if (entry.role === "reasoning") return heading("💭 Reasoning", `*${escapeMd(entry.text)}*`, { escape: false });
  if (entry.role === "system") return heading("ℹ️ System", entry.text);

  if (entry.role === "event") {
    if (entry.kind === "error") return heading("❌ Error", entry.text);
    if (entry.kind === "warning") return heading("⚠️ Warning", entry.text);
    if (entry.kind === "info") return heading("ℹ️ Info", entry.text);
    if (entry.kind === "notification") {
      let out = heading("ℹ️ Notification", entry.text);
      if (entry.detail) {
        out += `\n<details>\n<summary>Detail</summary>\n\n${entry.detail}\n\n</details>\n`;
      }
      return out;
    }
    if (entry.kind === "handoff") {
      const data = entry.data ?? {};
      const repo = (data.repository ?? {}) as { owner?: string; name?: string; branch?: string | null };
      const repoLine = repo.owner && repo.name
        ? `${repo.owner}/${repo.name}${repo.branch ? ` (${repo.branch})` : ""}`
        : "(unknown)";
      const summary = typeof data.summary === "string" && data.summary ? `\n**Summary:** ${data.summary}` : "";
      return `### 🔄 Session Handoff\n\n**Repository:** ${repoLine}${summary}\n`;
    }
    if (entry.kind === "compaction") return `### ◌ Conversation Compacted\n`;
    if (entry.kind === "task_complete") return `### ✓ Task Complete\n\n${entry.text}\n`;
    if (entry.kind === "subagent") {
      const data = entry.data ?? {};
      const name = entry.title ?? "subagent";
      const bits: string[] = [];
      if (typeof data.model === "string" && data.model) bits.push(data.model);
      if (data.failed === true) bits.push("failed");
      const meta = bits.length ? `\n\n<sub>${bits.join(" · ")}</sub>` : "";
      const desc = entry.text ? `\n\n${escapeMd(entry.text)}` : "";
      const err = typeof data.error === "string" && data.error ? `\n\n**Error:** ${escapeMd(data.error)}` : "";
      return `### 🤖 Subagent: ${escapeMd(name)}${desc}${meta}${err}\n`;
    }
    if (entry.kind === "skill") {
      const name = entry.title ?? "skill";
      const desc = entry.text ? `\n\n${escapeMd(entry.text)}` : "";
      return `### ✨ Skill: ${escapeMd(name)}${desc}\n`;
    }
    if (entry.kind === "plan") return heading("📋 Plan", entry.text);
  }
  return heading(`📌 ${entry.kind}`, entry.text);
}

function heading(label: string, text: string, opts: { escape?: boolean } = {}): string {
  const body = opts.escape === false ? text : escapeMd(text);
  return `### ${label}\n\n${body}\n`;
}

function renderTool(tool: ToolDetail): string {
  const name = tool.name ?? "(unnamed)";
  const emoji = resultEmoji(tool.result?.type);
  let out = `### ${emoji} \`${name}\``;
  if (tool.intentionSummary) out += `\n\n**${tool.intentionSummary}**`;
  const argsBlock = renderToolArgs(name, tool.arguments);
  if (argsBlock) out += `\n\n${argsBlock}`;
  out += `\n\n`;

  if (tool.partialOutput) {
    const label = outputLabel(tool.partialOutput, name);
    out += `<details>\n<summary>Partial Output • ${label}</summary>\n\n${fence(tool.partialOutput)}\n\n</details>\n\n`;
  }

  const result = tool.result;
  if (!result) return out;
  if (result.type === "rejected") return out + `_Rejected by user_\n\n`;
  if (!hasResultBody(result.type)) return out;

  const log = result.log ?? "";
  if (!log) return out;
  const isDiff = isDiffOutput(log);
  const rendered = result.markdown
    ? log
    : (isDiff ? fence(log.replace(/\s+$/u, ""), "diff") : fence(isDiff ? log.replace(/\s+$/u, "") : log));

  if (!isShort(log) && !containsDetailsTag(log)) {
    const summary = outputLabel(log, name);
    const tail = result.markdown ? log : (isDiff ? fence(log.replace(/\s+$/u, ""), "diff") : fence(log.trimEnd()));
    out += `<details>\n<summary>${summary}</summary>\n\n${tail}\n\n</details>\n\n`;
  } else {
    out += `${rendered}\n\n`;
  }
  return out;
}

function hasResultBody(kind: ToolResultKind): boolean {
  return kind === "success" || kind === "failure" || kind === "denied";
}

function resultEmoji(kind?: ToolResultKind): string {
  if (kind === "success") return "✅";
  if (kind === "failure") return "❌";
  if (kind === "rejected") return "🚫";
  if (kind === "denied") return "⛔";
  return "🔧";
}

function renderToolArgs(name: string, args: unknown): string {
  const compact = toolArgSummary(name, args);
  if (compact) return `\`${compact}\``;
  if (args === undefined || args === null) return "";
  let body: string;
  try {
    body = JSON.stringify(args, null, 2);
  } catch {
    body = String(args);
  }
  return `<details>\n<summary>Arguments</summary>\n\n${fence(body, "json")}\n\n</details>`;
}

function toolArgSummary(name: string, args: unknown): string | null {
  if (!args || typeof args !== "object" || Array.isArray(args)) return null;
  const a = args as Record<string, unknown>;
  if (name === "grep" || name === "rg") {
    const parts = [`"${str(a.pattern)}"`];
    if (a.glob) parts.push(`in ${str(a.glob)}`);
    else if (a.type) parts.push(`in ${str(a.type)} files`);
    const p = pathsSummary(a);
    if (p) parts.push(`(${p})`);
    return parts.join(" ");
  }
  if (name === "glob") {
    const parts = [`"${str(a.pattern)}"`];
    const p = pathsSummary(a);
    if (p) parts.push(`in ${p}`);
    return parts.join(" ");
  }
  if (name === "bash" || name === "local_shell") {
    return `$ ${str(a.command)}`;
  }
  if (name === "view") {
    const path = str(a.path);
    const range = a.view_range;
    if (Array.isArray(range) && range.length === 2) {
      return `${path} (lines ${String(range[0])}-${String(range[1])})`;
    }
    return path;
  }
  if (name === "edit" || name === "create") return str(a.path);
  return null;
}

function pathsSummary(a: Record<string, unknown>): string | null {
  const raw = a.paths ?? a.path;
  if (!raw) return null;
  const items = (typeof raw === "string" ? [raw] : Array.isArray(raw) ? raw.map(String) : []).filter((x) => x && x !== ".");
  return items.length > 0 ? items.join(", ") : null;
}

function str(value: unknown): string {
  return value == null ? "" : String(value);
}

function escapeMd(text: string): string {
  return (text ?? "").replace(/</g, "\\<").replace(/>/g, "\\>");
}

function isShort(text: string, max = 5): boolean {
  return text.split("\n").length <= max;
}

function isDiffOutput(text: string): boolean {
  return text.includes("diff --git") || (text.includes("@@") && (text.includes("+++") || text.includes("---")));
}

function containsDetailsTag(text: string): boolean {
  return text.includes("</details>") || text.includes("<details") || text.includes("</summary>") || text.includes("<summary");
}

function fence(text: string, lang = ""): string {
  const maxBackticks = longestBacktickRun(text);
  const fenceLen = Math.max(3, maxBackticks + 1);
  const bar = "`".repeat(fenceLen);
  return `${bar}${lang}\n${text}\n${bar}`;
}

function longestBacktickRun(text: string): number {
  let max = 0;
  let run = 0;
  for (const ch of text) {
    if (ch === "`") {
      run += 1;
      if (run > max) max = run;
    } else {
      run = 0;
    }
  }
  return max;
}

function outputLabel(text: string, name: string | undefined): string {
  const lines = text.split("\n").filter((line) => line.trim());
  const n = lines.length;
  if (n === 0) return "No output";
  if (name === "grep" || name === "rg" || name === "glob") return `${n} ${n === 1 ? "match" : "matches"}`;
  if (name === "view" || name === "bash" || name === "local_shell") return `${n} line${n === 1 ? "" : "s"}`;
  const preview = lines[0]!.slice(0, 60);
  return n === 1 ? preview : `${n} lines`;
}

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
}
