/**
 * Generate `src/html/assets.generated.ts` by inlining the third-party assets
 * the HTML renderer used to read from `node_modules` at runtime:
 *
 *   - lucide-static SVG icons (only the ones the renderer references)
 *   - the KaTeX stylesheet, with its `.woff2` fonts embedded as data URLs
 *
 * Reading those files with `require.resolve` + `readFileSync` only works when
 * the package sits inside an installed `node_modules` tree. That breaks for the
 * two distribution targets we care about (a relocated single-file `npm i -g
 * github:` bundle, and a `bun build --compile` binary with no `node_modules` on
 * disk). Baking the bytes into a plain TS module makes the renderer
 * self-contained and bundler-agnostic: tsc, esbuild and bun all treat it as
 * ordinary string constants.
 *
 * Run automatically by scripts/bundle.mjs before every bundle.
 */
import { createRequire } from "node:module";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const require = createRequire(join(root, "package.json"));
const srcIndex = join(root, "src", "html", "index.tsx");
const outFile = join(root, "src", "html", "assets.generated.ts");

/* ── icon names ─────────────────────────────────────────────────────────────
 * Most icons are referenced literally via `<Icon name="…">` or a `icon: "…"`
 * field, so scan the source for those. A handful are returned from helper
 * functions (e.g. `resultIcon`) as bare string literals that a generic scan
 * can't distinguish from other strings, so list those explicitly. Names that
 * don't exist in the installed lucide-static are skipped; the renderer's
 * `icon()` fallback renders an empty <svg> for them, matching the previous
 * runtime behaviour. */
const EXTRA_ICON_NAMES = ["check", "x", "ban", "triangle-alert", "hourglass"];

function collectIconNames() {
  const source = readFileSync(srcIndex, "utf8");
  const names = new Set(EXTRA_ICON_NAMES);
  for (const match of source.matchAll(/name="([a-z][a-z0-9-]*)"/g)) names.add(match[1]);
  for (const match of source.matchAll(/icon:\s*"([a-z][a-z0-9-]*)"/g)) names.add(match[1]);
  return [...names].sort();
}

function loadIcons() {
  const iconRoot = join(dirname(require.resolve("lucide-static/package.json")), "icons");
  const icons = {};
  const missing = [];
  for (const name of collectIconNames()) {
    const file = join(iconRoot, `${name}.svg`);
    if (!existsSync(file)) {
      missing.push(name);
      continue;
    }
    icons[name] = readFileSync(file, "utf8").trim();
  }
  if (missing.length) {
    console.warn(`[gen-assets] lucide-static has no icon for: ${missing.join(", ")} (renders empty)`);
  }
  return icons;
}

/* ── KaTeX stylesheet ────────────────────────────────────────────────────────
 * KaTeX ships web fonts referenced by relative `url(fonts/*.woff2)` paths. For
 * a fully self-contained HTML report those fonts must be embedded. Replicate
 * the previous runtime transform verbatim: for every `src:` declaration keep
 * only the `.woff2` source and inline it as a base64 data URL. */
function loadKatexCss() {
  const cssPath = require.resolve("katex/dist/katex.min.css");
  const cssDir = dirname(cssPath);
  const raw = readFileSync(cssPath, "utf8");
  return raw.replace(/src:([^}]*)/g, (_match, sources) => {
    const woff2 = sources.split(",").find((source) => source.includes(".woff2"));
    if (!woff2) return "";
    const embedded = woff2.replace(
      /url\((?:["']?)(fonts\/[^)"']+\.woff2)(?:["']?)\)/,
      (_url, relativePath) => {
        const base64 = readFileSync(join(cssDir, relativePath)).toString("base64");
        return `url(data:font/woff2;base64,${base64})`;
      },
    );
    return `src:${embedded}`;
  });
}

const icons = loadIcons();
const katexCss = loadKatexCss();

const banner =
  "// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit.\n" +
  "// Inlines lucide-static icons and the KaTeX stylesheet so the HTML renderer\n" +
  "// needs no node_modules assets at runtime. Regenerate with the html build.\n\n";

const body =
  `export const ICONS: Record<string, string> = ${JSON.stringify(icons, null, 2)};\n\n` +
  `export const KATEX_CSS = ${JSON.stringify(katexCss)};\n`;

writeFileSync(outFile, banner + body);
console.log(`[gen-assets] wrote ${outFile} (${Object.keys(icons).length} icons, katex css ${katexCss.length} bytes)`);
