import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import ReactMarkdown from "react-markdown";
import rehypeKatex from "rehype-katex";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import type { ParsedSession, TimelineEntry, TimelineRole } from "@session-recall/core";

const require = createRequire(import.meta.url);

export function renderSessionHtml(session: ParsedSession): string {
  const markup = renderToStaticMarkup(<Report session={session} />);
  return `<!doctype html>${markup}`;
}

function Report({ session }: { session: ParsedSession }) {
  const counts = countRoles(session.entries);
  const roles = (["user", "assistant", "tool", "reasoning", "system", "event"] as TimelineRole[])
    .filter((role) => counts[role]);

  return (
    <html lang="en" className="dark">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{`${session.agent} session ${session.id}`}</title>
        <style dangerouslySetInnerHTML={{ __html: `${katexCss()}\n${css}` }} />
      </head>
      <body>
        <header className="topbar">
          <div className="title-row">
            <div>
              <h1>🌀 {session.title ?? `${session.agent} session`}</h1>
              <p>
                <code>{session.agent}</code> · <code>{session.id}</code>
              </p>
            </div>
            <div className="meta">
              {session.cwd && <span>{session.cwd}</span>}
              {session.startedAt && <span>{formatDate(session.startedAt)}</span>}
              <span>{session.entries.length} entries</span>
            </div>
          </div>

          <div className="controls">
            <label className="search">
              <span>⌕</span>
              <input id="search" placeholder="Search (/)" autoComplete="off" />
            </label>

            <div className="filters" aria-label="entry filters">
              {roles.map((role) => (
                <button key={role} type="button" className={`filter ${role}`} data-filter={role} aria-pressed="true">
                  {roleLabel(role)} <small>{counts[role]}</small>
                </button>
              ))}
            </div>

            <div className="buttons">
              <button type="button" id="prev-user" title="Previous user message">↑ user</button>
              <button type="button" id="next-user" title="Next user message">↓ user</button>
              <button type="button" id="collapse-all">Collapse</button>
              <button type="button" id="expand-all">Expand</button>
              <button type="button" id="toggle-sidebar">Map</button>
              <button type="button" id="toggle-compact">Compact</button>
              <button type="button" id="toggle-theme">Theme</button>
            </div>
          </div>
        </header>

        <div className="layout">
          <aside id="sidebar">
            <nav>
              {session.entries.map((entry) => (
                <a key={entry.index} href={`#entry-${entry.index}`} data-nav-role={entry.role}>
                  <span>#{entry.index + 1}</span>
                  <strong>{roleLabel(entry.role)}</strong>
                  <em>{firstLine(entry.title ?? entry.text)}</em>
                </a>
              ))}
            </nav>
          </aside>

          <main>
            {session.entries.map((entry) => (
              <Entry key={entry.index} entry={entry} />
            ))}
            <footer>
              Generated by <strong>session-recall</strong>. This file is self-contained and works offline.
            </footer>
          </main>
        </div>

        <script dangerouslySetInnerHTML={{ __html: clientScript }} />
      </body>
    </html>
  );
}

function Entry({ entry }: { entry: TimelineEntry }) {
  const isMarkdown = entry.role === "assistant" || entry.role === "reasoning";
  const open = entry.role === "user" || entry.role === "event";
  return (
    <details
      id={`entry-${entry.index}`}
      className={`entry ${entry.role}`}
      data-role={entry.role}
      data-text={`${entry.role} ${entry.kind} ${entry.title ?? ""} ${entry.text}`.toLowerCase()}
      open={open}
    >
      <summary>
        <span className="chevron">›</span>
        <span className="badge">#{entry.index + 1}</span>
        <span className="role">{roleLabel(entry.role)}</span>
        <strong>{entry.title ?? entry.kind}</strong>
        <span className="snippet">{firstLine(entry.text)}</span>
        {entry.timestamp && <time>{formatTime(entry.timestamp)}</time>}
      </summary>
      <div className="body">
        {isMarkdown ? <Markdown text={entry.text} /> : <PreBlock text={entry.text} />}
      </div>
    </details>
  );
}

function Markdown({ text }: { text: string }) {
  return (
    <div className="markdown">
      <ReactMarkdown remarkPlugins={[remarkGfm, remarkMath]} rehypePlugins={[rehypeKatex]}>
        {text}
      </ReactMarkdown>
    </div>
  );
}

function PreBlock({ text }: { text: string }) {
  return <pre className="plain">{text}</pre>;
}

function countRoles(entries: TimelineEntry[]): Record<TimelineRole, number> {
  const counts: Record<TimelineRole, number> = {
    user: 0,
    assistant: 0,
    tool: 0,
    reasoning: 0,
    system: 0,
    event: 0,
  };
  for (const entry of entries) counts[entry.role] += 1;
  return counts;
}

function roleLabel(role: TimelineRole): string {
  return {
    user: "User",
    assistant: "Assistant",
    tool: "Tool",
    reasoning: "Reasoning",
    system: "System",
    event: "Event",
  }[role];
}

function firstLine(text: string): string {
  const line = text.split("\n").find((item) => item.trim())?.trim() ?? "";
  return line.length > 100 ? `${line.slice(0, 100)}…` : line;
}

function formatDate(timestamp: string): string {
  const d = new Date(timestamp);
  return Number.isNaN(d.getTime()) ? timestamp : d.toLocaleString();
}

function formatTime(timestamp: string): string {
  const d = new Date(timestamp);
  if (Number.isNaN(d.getTime())) return timestamp;
  return d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false });
}

function katexCss(): string {
  try {
    return readFileSync(require.resolve("katex/dist/katex.min.css"), "utf8");
  } catch {
    return "";
  }
}

const clientScript = String.raw`
(() => {
  const $ = (id) => document.getElementById(id);
  const entries = () => [...document.querySelectorAll('.entry')];
  const navLinks = () => [...document.querySelectorAll('#sidebar a')];
  const activeRoles = new Set([...document.querySelectorAll('.filter[aria-pressed="true"]')].map((b) => b.dataset.filter));

  function applyFilters() {
    const q = ($('search')?.value || '').trim().toLowerCase();
    const roles = new Set([...document.querySelectorAll('.filter[aria-pressed="true"]')].map((b) => b.dataset.filter));
    entries().forEach((entry) => {
      const visible = roles.has(entry.dataset.role) && (!q || (entry.dataset.text || '').includes(q));
      entry.hidden = !visible;
    });
    navLinks().forEach((link) => {
      const target = document.querySelector(link.getAttribute('href'));
      link.hidden = !target || target.hidden;
    });
  }

  function setAll(open) {
    entries().forEach((entry) => { if (!entry.hidden) entry.open = open; });
  }

  function jumpUser(dir) {
    const users = entries().filter((entry) => entry.dataset.role === 'user' && !entry.hidden);
    const y = window.scrollY + 160;
    const target = dir > 0
      ? users.find((entry) => entry.offsetTop > y)
      : users.filter((entry) => entry.offsetTop < y - 40).at(-1);
    target?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }

  $('search')?.addEventListener('input', applyFilters);
  document.addEventListener('keydown', (event) => {
    if (event.key === '/' && !['INPUT', 'TEXTAREA'].includes(document.activeElement?.tagName || '')) {
      event.preventDefault();
      $('search')?.focus();
    }
  });
  document.querySelectorAll('.filter').forEach((button) => {
    button.addEventListener('click', () => {
      const next = button.getAttribute('aria-pressed') !== 'true';
      button.setAttribute('aria-pressed', String(next));
      applyFilters();
    });
  });
  $('collapse-all')?.addEventListener('click', () => setAll(false));
  $('expand-all')?.addEventListener('click', () => setAll(true));
  $('prev-user')?.addEventListener('click', () => jumpUser(-1));
  $('next-user')?.addEventListener('click', () => jumpUser(1));
  $('toggle-sidebar')?.addEventListener('click', () => document.body.classList.toggle('no-sidebar'));
  $('toggle-compact')?.addEventListener('click', () => {
    document.body.classList.toggle('compact');
    localStorage.setItem('session-recall-compact', document.body.classList.contains('compact') ? '1' : '0');
  });
  $('toggle-theme')?.addEventListener('click', () => {
    document.documentElement.classList.toggle('dark');
    document.documentElement.classList.toggle('light');
  });
  if (localStorage.getItem('session-recall-compact') === '1') document.body.classList.add('compact');
  applyFilters();
})();
`;

const css = `
:root {
  color-scheme: light;
  --bg:#ffffff; --panel:#f6f8fa; --panel2:#eef1f4; --text:#1f2328; --muted:#59636e;
  --border:#d8dee4; --code:#f6f8fa; --blue:#0969da; --green:#1a7f37; --violet:#8250df;
  --amber:#9a6700; --red:#cf222e; --gray:#6e7781;
}
.dark {
  color-scheme: dark;
  --bg:#0d1117; --panel:#161b22; --panel2:#1c2230; --text:#e6edf3; --muted:#9aa3b2;
  --border:#30363d; --code:#0b0f17; --blue:#58a6ff; --green:#3fb950; --violet:#a371f7;
  --amber:#d29922; --red:#ff7b72; --gray:#8b949e;
}
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--text); font:15px/1.65 ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif; }
.topbar { position:sticky; top:0; z-index:5; background:color-mix(in srgb, var(--bg) 90%, transparent); border-bottom:1px solid var(--border); backdrop-filter:blur(10px); }
.title-row { max-width:1280px; margin:0 auto; display:flex; justify-content:space-between; gap:24px; padding:14px 20px 8px; }
h1 { margin:0; font-size:19px; }
p { margin:4px 0 0; color:var(--muted); }
code { font-family:ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
.meta { display:flex; flex-direction:column; align-items:flex-end; gap:2px; color:var(--muted); font-size:12px; }
.controls { max-width:1280px; margin:0 auto; display:flex; align-items:center; flex-wrap:wrap; gap:8px; padding:0 20px 12px; }
.search { display:flex; align-items:center; gap:6px; height:34px; padding:0 10px; border:1px solid var(--border); border-radius:10px; background:var(--panel); }
.search input { width:240px; border:0; outline:0; background:transparent; color:var(--text); font:inherit; }
.filters { display:flex; flex-wrap:wrap; gap:5px; }
button { border:1px solid var(--border); background:var(--panel); color:var(--text); border-radius:999px; padding:6px 10px; cursor:pointer; }
button:hover { background:var(--panel2); }
.filter[aria-pressed="false"] { opacity:.45; }
.filter small { margin-left:4px; color:var(--muted); }
.filter.user { color:var(--blue); } .filter.assistant { color:var(--green); }
.filter.tool { color:var(--violet); } .filter.reasoning { color:var(--amber); }
.filter.system, .filter.event { color:var(--gray); }
.buttons { margin-left:auto; display:flex; flex-wrap:wrap; gap:5px; }
.layout { max-width:1280px; margin:0 auto; display:grid; grid-template-columns:260px minmax(0, 1fr); gap:20px; padding:20px; }
body.no-sidebar .layout { grid-template-columns:1fr; }
body.no-sidebar #sidebar { display:none; }
#sidebar { position:sticky; top:116px; align-self:start; max-height:calc(100vh - 132px); overflow:auto; }
#sidebar nav { display:flex; flex-direction:column; gap:4px; }
#sidebar a { display:grid; grid-template-columns:auto auto minmax(0, 1fr); gap:6px; padding:5px 8px; color:var(--muted); text-decoration:none; border-radius:8px; font-size:13px; }
#sidebar a:hover { background:var(--panel); color:var(--text); }
#sidebar em { overflow:hidden; white-space:nowrap; text-overflow:ellipsis; font-style:normal; }
main { min-width:0; }
.entry { scroll-margin-top:130px; margin:0 0 12px; background:var(--panel); border:1px solid var(--border); border-left-width:3px; border-radius:12px; overflow:hidden; }
.entry.user { border-left-color:var(--blue); } .entry.assistant { border-left-color:var(--green); }
.entry.tool { border-left-color:var(--violet); } .entry.reasoning { border-left-color:var(--amber); }
.entry.system, .entry.event { border-left-color:var(--gray); }
.entry summary { display:flex; align-items:center; gap:9px; padding:10px 13px; cursor:pointer; list-style:none; }
.entry summary::-webkit-details-marker { display:none; }
.entry[open] .chevron { transform:rotate(90deg); }
.chevron { color:var(--muted); transition:transform .15s ease; font-size:18px; }
.badge { border:1px solid var(--border); border-radius:7px; padding:1px 7px; color:var(--muted); font-size:12px; font-weight:700; }
.role { font-weight:700; }
.entry.user .role { color:var(--blue); } .entry.assistant .role { color:var(--green); }
.entry.tool .role { color:var(--violet); } .entry.reasoning .role { color:var(--amber); }
.entry.system .role, .entry.event .role { color:var(--gray); }
.snippet { min-width:0; flex:1; overflow:hidden; white-space:nowrap; text-overflow:ellipsis; color:var(--muted); font-size:13px; }
time { color:var(--muted); font-size:12px; }
.body { border-top:1px solid var(--border); padding:13px; }
.plain, .markdown pre { margin:0; white-space:pre-wrap; word-break:break-word; overflow:auto; border:1px solid var(--border); border-radius:10px; background:var(--code); padding:12px; font:13px/1.55 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
.markdown > *:first-child { margin-top:0; } .markdown > *:last-child { margin-bottom:0; }
.markdown h1, .markdown h2, .markdown h3 { line-height:1.3; margin:1em 0 .4em; }
.markdown p, .markdown ul, .markdown ol { margin:.55em 0; }
.markdown ul, .markdown ol { padding-left:1.5em; }
.markdown blockquote { margin:.7em 0; padding-left:1em; border-left:3px solid var(--border); color:var(--muted); }
.markdown table { border-collapse:collapse; display:block; overflow:auto; margin:.8em 0; }
.markdown th, .markdown td { border:1px solid var(--border); padding:6px 10px; }
.markdown th { background:var(--panel2); }
.markdown :not(pre) > code { background:var(--panel2); border:1px solid var(--border); border-radius:5px; padding:.1em .35em; }
.katex-display { overflow-x:auto; overflow-y:hidden; padding:.2em 0; }
footer { color:var(--muted); text-align:center; font-size:12px; padding:18px 0; }
.compact { font-size:14px; }
.compact .entry { margin-bottom:7px; }
.compact .entry summary { padding:7px 10px; }
.compact .body { padding:9px; }
.compact .plain, .compact .markdown pre { font-size:12px; padding:9px; }
@media (max-width: 860px) {
  .layout { grid-template-columns:1fr; }
  #sidebar { display:none; }
  .title-row { flex-direction:column; }
  .meta { align-items:flex-start; }
  .buttons { margin-left:0; }
}
`;
